wandb_version: 1

weights:
  desc: null
  value: yolov7-e6e.pt
cfg:
  desc: null
  value: cfg/training/yolov7-e6e.yaml
data:
  desc: null
  value: data/data.yaml
hyp:
  desc: null
  value:
    lr0: 0.01
    lrf: 0.1
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    cls: 0.3
    cls_pw: 1.0
    obj: 0.7
    obj_pw: 1.0
    iou_t: 0.2
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.2
    scale: 0.9
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.15
    copy_paste: 0.0
    paste_in: 0.15
    loss_ota: 1
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 4
img_size:
  desc: null
  value:
  - 640
  - 640
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
evolve:
  desc: null
  value: false
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: ''
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
adam:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
workers:
  desc: null
  value: 4
project:
  desc: null
  value: runs/train
entity:
  desc: null
  value: null
name:
  desc: null
  value: yolov7-e6e
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
linear_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
save_period:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
v5_metric:
  desc: null
  value: false
world_size:
  desc: null
  value: 1
global_rank:
  desc: null
  value: -1
save_dir:
  desc: null
  value: runs/train/yolov7-e6e40
total_batch_size:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.2.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699530226.757106
    t:
      1:
      - 1
      - 11
      - 41
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 55
      - 105
      3:
      - 13
      - 16
      - 19
      - 23
      4: 3.9.18
      5: 0.15.11
      6: 4.2.1
      8:
      - 5
      13: linux-x86_64
opt:
  desc: null
  value:
    weights: yolov7-e6e.pt
    cfg: cfg/training/yolov7-e6e.yaml
    data: data/data.yaml
    hyp:
      lr0: 0.01
      lrf: 0.1
      momentum: 0.937
      weight_decay: 0.0005
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      warmup_bias_lr: 0.1
      box: 0.05
      cls: 0.3
      cls_pw: 1.0
      obj: 0.7
      obj_pw: 1.0
      iou_t: 0.2
      anchor_t: 4.0
      fl_gamma: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      degrees: 0.0
      translate: 0.2
      scale: 0.9
      shear: 0.0
      perspective: 0.0
      flipud: 0.0
      fliplr: 0.5
      mosaic: 1.0
      mixup: 0.15
      copy_paste: 0.0
      paste_in: 0.15
      loss_ota: 1
    epochs: 20
    batch_size: 4
    img_size:
    - 640
    - 640
    rect: false
    resume: false
    nosave: false
    notest: false
    noautoanchor: false
    evolve: false
    bucket: ''
    cache_images: false
    image_weights: false
    device: ''
    multi_scale: false
    single_cls: false
    adam: false
    sync_bn: false
    local_rank: -1
    workers: 4
    project: runs/train
    entity: null
    name: yolov7-e6e
    exist_ok: false
    quad: false
    linear_lr: false
    label_smoothing: 0.0
    upload_dataset: false
    bbox_interval: -1
    save_period: -1
    artifact_alias: latest
    v5_metric: false
    world_size: 1
    global_rank: -1
    save_dir: runs/train/yolov7-e6e40
    total_batch_size: 4
data_dict:
  desc: null
  value:
    train: /home/vivek.trivedi/synthetic_data_for_challenge/images
    val: /home/vivek.trivedi/yolo_challenge/train/images
    test: /home/vivek.trivedi/yolo_challenge/test/images
    nc: 10
    names:
    - pedestrian
    - people
    - bicycle
    - car
    - van
    - truck
    - tricycle
    - awning-tricycle
    - bus
    - motor
